# Generated by Django 4.1 on 2022-10-14 06:12

import ckeditor.fields
import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("fantasy", "Fantasy"),
                            ("sci-fi", "Sci-Fi"),
                            ("romance", "Romance"),
                            ("mystery", "Mystery"),
                            ("biography", "Biography"),
                            ("thriller", "Thriller"),
                            ("drama", "Drama"),
                            ("horror", "Horror"),
                            ("history", "History"),
                            ("western", "Western"),
                            ("non-fiction", "Non-Fiction"),
                            ("poetry", "Poetry"),
                            ("children", "Children"),
                            ("self-help", "Self-Help"),
                            ("religion", "Religion"),
                            ("science", "Science"),
                            ("programming", "Programming"),
                            ("history", "History"),
                            ("other", "Other"),
                            ("fiction,", "Fiction"),
                        ],
                        max_length=15,
                    ),
                ),
                ("year", models.IntegerField(default=0)),
                ("language", models.CharField(default="English", max_length=255)),
                (
                    "description",
                    ckeditor.fields.RichTextField(blank=True, max_length=1000),
                ),
                (
                    "cover_image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="cover_image"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, editable=False),
                ),
                (
                    "book",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="book_file"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"),
                                 ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("slug", models.SlugField(editable=False, unique=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
