# Generated by Django 4.1 on 2022-10-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cozylibrary", "0003_alter_book_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(editable=False, max_length=15, unique=True),
        ),
    ]
