# Generated by Django 4.0.5 on 2022-07-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozylibrary', '0010_alter_book_options_remove_book_price_book_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('sci-fi', 'Sci-Fi'), ('romance', 'Romance'), ('mystery', 'Mystery'), ('biography', 'Biography'), ('thriller', 'Thriller'), ('drama', 'Drama'), ('horror', 'Horror'), ('history', 'History'), ('western', 'Western'), ('non-fiction', 'Non-Fiction'), ('poetry', 'Poetry'), ('children', 'Children'), ('self-help', 'Self-Help'), ('religion', 'Religion'), ('science', 'Science'), ('programming', 'Programming'), ('history', 'History'), ('other', 'Other')], default='other', max_length=15),
        ),
    ]
