# Generated by Django 4.0.5 on 2022-08-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozylibrary', '0015_alter_book_book_alter_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('sci-fi', 'Sci-Fi'), ('romance', 'Romance'), ('mystery', 'Mystery'), ('biography', 'Biography'), ('thriller', 'Thriller'), ('drama', 'Drama'), ('horror', 'Horror'), ('history', 'History'), ('western', 'Western'), ('non-fiction', 'Non-Fiction'), ('poetry', 'Poetry'), ('children', 'Children'), ('self-help', 'Self-Help'), ('religion', 'Religion'), ('science', 'Science'), ('programming', 'Programming'), ('history', 'History'), ('other', 'Other'), ('fiction,', 'Fiction')], max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
