# Generated by Django 4.0.5 on 2022-08-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozylibrary', '0017_alter_book_book_alter_book_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='views',
        ),
    ]
